[tool.poetry]
name = "wpp-api-integration"
version = "0.1.0"
description = ""
authors = ["Lorenzo Uriel <lorenzouriel394@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
